-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 19:13:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customerId` INT NOT NULL,
  `firstName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `contactInfo` VARCHAR(255) NULL,
  `PaymentDetails` VARCHAR(255) NULL,
  PRIMARY KEY (`customerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EquipmentType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipmentType` (
  `typeID` INT NOT NULL,
  `typeName` VARCHAR(255) NULL,
  PRIMARY KEY (`typeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `equipmentID` INT NOT NULL,
  `Brand` VARCHAR(45) NULL,
  `Condition` VARCHAR(45) NULL,
  `typeID` INT NOT NULL,
  PRIMARY KEY (`equipmentID`, `typeID`),
  INDEX `fk_Equipment_EquipmentType1_idx` (`typeID` ASC) VISIBLE,
  CONSTRAINT `fk_Equipment_EquipmentType1`
    FOREIGN KEY (`typeID`)
    REFERENCES `mydb`.`EquipmentType` (`typeID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rental` (
  `rentalID` INT NOT NULL,
  `rentalDate` DATE NULL,
  `returnDate` DATE NULL,
  `Price` DECIMAL(10,2) NULL,
  `equipmentID` INT NOT NULL,
  `customerId` INT NOT NULL,
  PRIMARY KEY (`rentalID`, `customerId`, `equipmentID`),
  INDEX `fk_Rental_Equipment1_idx` (`equipmentID` ASC) VISIBLE,
  INDEX `fk_Rental_Customer1_idx` (`customerId` ASC) VISIBLE,
  CONSTRAINT `fk_Rental_Equipment1`
    FOREIGN KEY (`equipmentID`)
    REFERENCES `mydb`.`Equipment` (`equipmentID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Rental_Customer1`
    FOREIGN KEY (`customerId`)
    REFERENCES `mydb`.`Customer` (`customerId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EquipmentMaintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipmentMaintenance` (
  `maintenanceID` INT NOT NULL,
  `maintenanceDate` DATE NULL,
  `maintenanceType` VARCHAR(100) NULL,
  `equipmentID` INT NOT NULL,
  PRIMARY KEY (`maintenanceID`, `equipmentID`),
  INDEX `fk_EquipmentMaintenance_Equipment1_idx` (`equipmentID` ASC) VISIBLE,
  CONSTRAINT `fk_EquipmentMaintenance_Equipment1`
    FOREIGN KEY (`equipmentID`)
    REFERENCES `mydb`.`Equipment` (`equipmentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `staffID` INT NOT NULL,
  `firstName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `Role` VARCHAR(100) NULL,
  `contactDetails` VARCHAR(255) NULL,
  PRIMARY KEY (`staffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lessons` (
  `lessonID` INT NOT NULL,
  `description` TEXT NULL,
  `difficultyLevel` VARCHAR(50) NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`lessonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructors` (
  `instructorID` INT NOT NULL,
  `staffID` INT NOT NULL,
  PRIMARY KEY (`instructorID`, `staffID`),
  INDEX `fk_Instructors_Staff1_idx` (`staffID` ASC) VISIBLE,
  CONSTRAINT `fk_Instructors_Staff1`
    FOREIGN KEY (`staffID`)
    REFERENCES `mydb`.`Staff` (`staffID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LessonBookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LessonBookings` (
  `bookingID` INT NOT NULL,
  `bookingDate` DATE NULL,
  `customerId` INT NOT NULL,
  `instructorID` INT NOT NULL,
  `lessonID` INT NOT NULL,
  PRIMARY KEY (`bookingID`, `lessonID`, `instructorID`, `customerId`),
  INDEX `fk_LessonBookings_Customer1_idx` (`customerId` ASC) VISIBLE,
  INDEX `fk_LessonBookings_Instructors1_idx` (`instructorID` ASC) VISIBLE,
  INDEX `fk_LessonBookings_Lessons1_idx` (`lessonID` ASC) VISIBLE,
  CONSTRAINT `fk_LessonBookings_Customer1`
    FOREIGN KEY (`customerId`)
    REFERENCES `mydb`.`Customer` (`customerId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LessonBookings_Instructors1`
    FOREIGN KEY (`instructorID`)
    REFERENCES `mydb`.`Instructors` (`instructorID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LessonBookings_Lessons1`
    FOREIGN KEY (`lessonID`)
    REFERENCES `mydb`.`Lessons` (`lessonID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

