INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Jones', 'Powder Snow Snowboard', 2, False, '2024-01-07', 51.16, 153);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Pro Model Snowboard', 2, False, '2024-01-03', 78.78, 147);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Blizzard', 'Backcountry Ski Set', 1, False, '2024-02-02', 48.73, 161);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Burton', 'Freestyle Board', 2, True, '2024-01-17', 61.28, 155);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'Competition Grade Ski', 1, False, '2024-02-19', 89.24, 176);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Powder Snow Snowboard', 2, True, '2024-02-06', 74.21, 159);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Yonex', 'Pro Model Snowboard', 2, True, '2024-03-14', 68.78, 158);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Competition Grade Ski', 1, False, '2024-02-18', 69.76, 181);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Armada', 'Youth Ski', 1, False, '2024-01-22', 60.38, 134);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Pro Model Snowboard', 2, True, '2024-03-31', 60.51, 141);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Dakine', 'Recreational Snowboard', 2, False, '2024-02-03', 62.02, 140);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Atomic', 'Competition Grade Ski', 1, False, '2024-03-04', 69.15, 149);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Freestyle Board', 2, True, '2024-01-10', 48.78, 158);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Armada', 'Pro Model Ski', 1, True, '2024-02-29', 59.63, 161);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Jones', 'Freestyle Board', 2, False, '2024-01-03', 66.43, 148);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Rossignol', 'Backcountry Ski Set', 1, False, '2024-02-23', 80.44, 180);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'Competition Grade Ski', 1, False, '2024-03-13', 60.57, 185);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('K2 Sports', 'Advanced Freeride Ski', 1, True, '2024-02-26', 47.47, 168);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Jones', 'Competition Grade Snowboard', 2, True, '2024-03-25', 86.63, 157);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Crapsack', 'All Mountain Snowboard', 2, True, '2024-01-04', 80.46, 161);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'Recreational Ski', 1, True, '2024-01-12', 60.51, 184);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Yonex', 'Advanced Freeride Board', 2, False, '2024-01-25', 45.43, 158);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Volkl', 'Freestyle Ski', 1, True, '2024-02-10', 78.39, 182);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Volkl', 'Park & Pipe Ski', 1, True, '2024-03-08', 52.33, 186);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Atomic', 'Youth Ski', 1, False, '2024-01-02', 65.59, 135);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'Youth Ski', 1, False, '2024-01-02', 49.89, 161);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Rossignol', 'Recreational Ski', 1, True, '2024-02-01', 63.83, 137);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nidecker', 'Youth Snowboard', 2, True, '2024-03-22', 50.28, 162);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Armada', 'Youth Ski', 1, False, '2024-03-17', 73.68, 168);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('K2 Sports', 'Freestyle Ski', 1, False, '2024-03-09', 63.48, 169);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Youth Ski', 1, False, '2024-01-14', 89.87, 161);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Freestyle Board', 2, True, '2024-02-06', 83.95, 160);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('K2 Sports', 'Youth Ski', 1, False, '2024-03-03', 54.89, 137);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Volkl', 'Competition Grade Ski', 1, False, '2024-02-04', 65.7, 156);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Blizzard', 'Competition Grade Ski', 1, False, '2024-03-26', 81.88, 167);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Backcountry Snowboard Set', 2, False, '2024-02-20', 87.79, 159);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Rossignol', 'Pro Model Ski', 1, False, '2024-03-26', 57.46, 148);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Atomic', 'Competition Grade Ski', 1, False, '2024-03-13', 72.13, 178);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'Youth Ski', 1, False, '2024-03-17', 89.17, 143);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Dakine', 'Competition Grade Snowboard', 2, True, '2024-02-19', 47.13, 155);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Volkl', 'Pro Model Ski', 1, True, '2024-01-11', 59.64, 181);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Competition Grade Snowboard', 2, True, '2024-02-16', 46.03, 149);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Atomic', 'Pro Model Ski', 1, False, '2024-01-03', 42.0, 161);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Backcountry Snowboard Set', 2, True, '2024-02-20', 73.88, 149);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Competition Grade Snowboard', 2, False, '2024-03-18', 42.9, 155);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Blizzard', 'Pro Model Ski', 1, True, '2024-03-02', 52.67, 183);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Recreational Snowboard', 2, False, '2024-01-09', 53.3, 158);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'Park & Pipe Ski', 1, False, '2024-01-16', 75.42, 145);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Yonex', 'Powder Snow Snowboard', 2, True, '2024-02-03', 71.17, 162);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Advanced Freeride Ski', 1, True, '2024-02-19', 56.56, 182);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Recreational Snowboard', 2, False, '2024-01-15', 67.12, 140);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nidecker', 'Competition Grade Snowboard', 2, True, '2024-02-03', 84.98, 155);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Armada', 'Competition Grade Ski', 1, False, '2024-02-06', 66.54, 153);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Pro Model Snowboard', 2, True, '2024-02-04', 75.31, 147);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Recreational Ski', 1, False, '2024-03-02', 78.71, 180);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('CamelBak', 'Youth Snowboard', 2, False, '2024-02-05', 70.27, 162);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Armada', 'Pro Model Ski', 1, False, '2024-01-09', 66.31, 156);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Capita', 'Park & Pipe Snowboard', 2, False, '2024-01-11', 77.2, 162);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Burton', 'Advanced Freeride Board', 2, True, '2024-03-11', 47.36, 142);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('K2 Sports', 'Youth Ski', 1, False, '2024-02-13', 68.21, 193);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Rossignol', 'Competition Grade Ski', 1, True, '2024-01-23', 74.71, 160);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Jones', 'All Mountain Snowboard', 2, False, '2024-03-28', 67.36, 146);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Capita', 'Backcountry Snowboard Set', 2, True, '2024-01-19', 71.62, 153);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Yonex', 'Youth Snowboard', 2, False, '2024-03-01', 65.47, 160);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'All Mountain Ski', 1, True, '2024-02-16', 63.87, 181);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Youth Ski', 1, False, '2024-01-06', 82.61, 158);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('CamelBak', 'Park & Pipe Snowboard', 2, True, '2024-04-01', 66.32, 151);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Volkl', 'Park & Pipe Ski', 1, False, '2024-02-19', 71.69, 177);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Advanced Freeride Board', 2, True, '2024-01-16', 48.08, 149);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Atomic', 'Powder Snow Ski', 1, False, '2024-03-06', 54.52, 157);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Rossignol', 'Recreational Ski', 1, True, '2024-03-05', 57.12, 178);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nordica', 'Freestyle Ski', 1, False, '2024-03-06', 46.45, 177);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Dakine', 'Backcountry Snowboard Set', 2, False, '2024-03-14', 79.67, 152);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Volkl', 'Competition Grade Ski', 1, True, '2024-03-07', 66.89, 156);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Recreational Ski', 1, True, '2024-02-09', 73.86, 184);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Capita', 'Competition Grade Snowboard', 2, False, '2024-02-26', 42.99, 159);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Jones', 'Freestyle Board', 2, True, '2024-01-08', 56.54, 154);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('CamelBak', 'Recreational Snowboard', 2, False, '2024-01-04', 51.33, 140);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Recreational Ski', 1, False, '2024-03-27', 55.72, 164);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Burton', 'Advanced Freeride Board', 2, True, '2024-04-01', 65.06, 140);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Dakine', 'Pro Model Snowboard', 2, False, '2024-01-31', 72.04, 148);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'Powder Snow Snowboard', 2, False, '2024-01-20', 42.97, 160);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nidecker', 'Backcountry Snowboard Set', 2, True, '2024-03-13', 54.23, 154);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Yonex', 'Competition Grade Snowboard', 2, True, '2024-01-05', 61.05, 140);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Crapsack', 'Recreational Snowboard', 2, True, '2024-02-04', 61.82, 159);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Capita', 'Recreational Snowboard', 2, False, '2024-02-18', 84.91, 156);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Dakine', 'All Mountain Snowboard', 2, True, '2024-02-22', 85.32, 153);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Dakine', 'Competition Grade Snowboard', 2, False, '2024-02-15', 43.15, 142);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('CamelBak', 'Recreational Snowboard', 2, True, '2024-03-05', 75.83, 160);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Jones', 'Advanced Freeride Board', 2, True, '2024-03-03', 89.04, 154);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Rossignol', 'Pro Model Ski', 1, False, '2024-02-19', 85.05, 135);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Jones', 'Park & Pipe Snowboard', 2, False, '2024-02-19', 48.88, 155);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Backcountry Snowboard Set', 2, True, '2024-03-24', 89.16, 148);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Freestyle Board', 2, True, '2024-03-05', 88.4, 158);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Volkl', 'Recreational Ski', 1, False, '2024-03-23', 40.11, 151);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Salomon', 'Pro Model Ski', 1, True, '2024-01-11', 82.51, 156);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Yonex', 'Recreational Snowboard', 2, True, '2024-03-17', 48.09, 146);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Patagonia', 'All Mountain Snowboard', 2, False, '2024-03-22', 76.01, 145);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Bataleon', 'Advanced Freeride Board', 2, False, '2024-01-20', 71.46, 146);
INSERT INTO `mydb`.`Equipment` (`Brand`, `Description`, `typeID`, `Availability`, `LastMaintenance`, `Price`, `Size`) VALUES ('Nidecker', 'Recreational Snowboard', 2, True, '2024-01-21', 66.59, 150);