# Generated by Django 5.0.3 on 2024-04-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chee_lessons', '0002_staff_instructor_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(choices=[('Half Day', 'Half Day'), ('Full Day', 'Full Day')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sport',
            field=models.CharField(choices=[('Ski', 'Ski'), ('Snowboard', 'Snowboard')], max_length=10, null=True),
        ),
    ]
