# Generated by Django 5.0.3 on 2024-04-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chee_lessons', '0003_remove_lesson_price_lesson_duration_lesson_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Kid', 'Kid')], max_length=5, null=True),
        ),
    ]
