# Generated by Django 5.0.3 on 2024-04-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chee_home', '0003_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
