# Generated by Django 5.0.3 on 2024-04-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('typeID', models.IntegerField(null=True)),
                ('availability', models.BooleanField(default=True)),
                ('lastMaintenance', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
